-- Migration: Vendor AI Assistant Settings & Messages Additions (2026-04-26)

-- 1. AI SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.vendor_ai_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    brand_id UUID REFERENCES public.brands(id) ON DELETE CASCADE NOT NULL UNIQUE,
    ai_enabled BOOLEAN DEFAULT true,
    auto_reply_enabled BOOLEAN DEFAULT false,
    auto_accept_orders BOOLEAN DEFAULT false,
    custom_instructions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.vendor_ai_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Vendors manage their AI settings." ON public.vendor_ai_settings;
CREATE POLICY "Vendors manage their AI settings." ON public.vendor_ai_settings 
FOR ALL USING (
    EXISTS (SELECT 1 FROM public.brands WHERE id = brand_id AND owner_id = auth.uid())
);

-- Trigger to auto-create AI settings when brand is created
CREATE OR REPLACE FUNCTION public.handle_new_brand_ai_settings()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.vendor_ai_settings (brand_id) VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Don't overwrite the existing trigger if it can just be added, but we need multiple actions
-- Let's just create an independent trigger
DROP TRIGGER IF EXISTS on_brand_created_ai ON public.brands;
CREATE TRIGGER on_brand_created_ai
AFTER INSERT ON public.brands
FOR EACH ROW EXECUTE FUNCTION public.handle_new_brand_ai_settings();

-- Initialize AI settings for existing brands
INSERT INTO public.vendor_ai_settings (brand_id)
SELECT id FROM public.brands
ON CONFLICT (brand_id) DO NOTHING;

-- 2. MESSAGES ENHANCEMENT
-- We add an `answered_by_ai` flag to track if a message was generated by the copilot
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS answered_by_ai BOOLEAN DEFAULT false;

-- Notify schema reload
NOTIFY pgrst, 'reload schema';
